// src/pages/tutorialsData.js

// Roles manejados en el sistema:
// 1: Administrador, 2: Cajero, 3: Farmaceutico, 4: Inventario

// Datos para los videos de los tutoriales
export const tutorials = [
  {
    id: 101,
    title: "Bienvenida: recorrido inicial y navegacion",
    section: "Resumen",
    roleAccess: [1, 2, 3, 4],
    contentType: "video",
    videoId: "dQw4w9WgXcQ",
  },
  {
    id: 201,
    title: "Inventario: ingresos, ajustes y vencimientos",
    section: "Inventario",
    roleAccess: [1, 3, 4],
    contentType: "video",
    videoId: "wWoQ7PFSYlk",
  },
  {
    id: 302,
    title: "Facturación: anulaciones y devoluciones",
    section: "Facturación",
    roleAccess: [1, 2],
    contentType: "video",
    videoId: "ESOjt2_yJrU",
  },
  {
    id: 401,
    title: "Usuarios y roles: altas, permisos y bloqueos",
    section: "Usuarios",
    roleAccess: [1],
    contentType: "video",
    videoId: "foE1mO2yM04",
  },

// Datos para los tutoriales en el acordeon
  {
    id: 501,
    title: "Reportes y estadisticas",
    section: "Reportes",
    roleAccess: [1, 2, 3, 4],
    contentType: "text",
    text: "Abre Reportes desde el menu. El tablero muestra ventas del dia, valor del inventario, lotes por vencer y productos bajo stock. Filtra ventas por fecha, ajusta el campo de dias para vencimientos y usa Refrescar para recargar. Revisa la tabla de ventas para ver metodo de pago, cliente y usuario.",
  },
  {
    id: 402,
    title: "Roles y permisos",
    section: "Usuarios",
    roleAccess: [1],
    contentType: "text",
    text: "Solo Administrador (rol 1) gestiona usuarios. En Usuarios crea o edita cuentas, asigna rol (1 Admin, 2 Cajero, 3 Farmaceutico, 4 Inventario) y activa/inactiva accesos. Admin tiene todo; Cajero factura y administra clientes; Farmaceutico consulta inventario y reportes; Inventario gestiona compras, lotes y reportes.",
  },
  {
    id: 301,
    title: "Registrar Venta",
    section: "Facturación",
    roleAccess: [1, 2],
    contentType: "text",
    text: "En Facturación/POS busca o crea cliente rapido, agrega productos (busqueda por nombre/codigo) y selecciona lote disponible. Ajusta cantidades, descuentos y verifica stock. Define metodo de pago y guarda: descuenta inventario, registra factura y se refleja en reportes. Usa devolucion/anulacion cuando corresponda.",
  },
  {
    id: 202,
    title: "Registrar Lotes",
    section: "Inventario",
    roleAccess: [1, 3, 4],
    contentType: "text",
    text: "En Inventario > Lotes elige Nuevo lote: selecciona producto, numero de lote, fechas de ingreso y vencimiento, cantidades por empaque/unidad, costo y precio de venta, descuento por empaque y marca. Al guardar se actualiza el stock del producto y se controla vencimiento. Puedes editar, desactivar o mover stock entre lotes.",
  },
  {
    id: 102,
    title: "Buenas practicas de uso",
    section: "Resumen",
    roleAccess: [1, 2, 3, 4],
    contentType: "text",
    text: "Configura nombre, logo, moneda y datos de soporte en Configuracion. Mantiene catalogo limpio (productos con categoria, unidad y stock minimo; proveedores con contacto; clientes con documento). Registra compras antes de vender para actualizar stock. Revisa vencimientos y bajo stock a diario en Reportes. Cierra sesion al terminar turno.",
  },
  {
    id: 503,
    title: "Compras y recepcion",
    section: "Compras",
    roleAccess: [1, 3, 4],
    contentType: "text",
    text: "En Inventario > Compras crea la orden con proveedor, fecha y referencia. Agrega items indicando producto, costo, cantidad y lote si lo conoces. Guarda y confirma la compra para que impacte inventario y cree/actualice lotes. Usa el buscador para localizar compras y ver su detalle.",
  },
  {
    id: 504,
    title: "Gestion de productos y categorias",
    section: "Productos",
    roleAccess: [1, 3, 4],
    contentType: "text",
    text: "Desde Productos crea o edita articulos con nombre, codigo, categoria, unidad de medida, stock minimo, precios y estado. Usa categorias y marcas para agrupar. Desactiva productos que ya no se venden para evitar que aparezcan en POS, pero conserva su historial.",
  },
  {
    id: 505,
    title: "Clientes y Facturación rapida",
    section: "Clientes",
    roleAccess: [1, 2],
    contentType: "text",
    text: "En Clientes busca por nombre/documento, crea nuevos con tipo y numero de documento, telefono y correo. Edita o inactiva registros duplicados. El POS reutiliza esta lista para facturar mas rapido y registrar ventas con datos correctos del cliente.",
  },
  {
    id: 506,
    title: "Configuracion y soporte",
    section: "Configuracion",
    roleAccess: [1],
    contentType: "text",
    text: "En Configuracion ajusta moneda y simbolo, datos de contacto de soporte, logo de la empresa y nombre comercial. Estos valores se guardan en el servidor, se reflejan en el login, navbar y reportes, y se cachean en sesion para cargar mas rapido.",
  },
  {
    id: 507,
    title: "Punto de venta (POS)",
    section: "Facturación",
    roleAccess: [1, 2],
    contentType: "text",
    text: "Desde Punto de Venta selecciona cliente, agrega productos y lotes, aplica descuentos y confirma el pago. Verifica siempre stock en la linea (color de alerta) y el subtotal antes de facturar. El POS respeta precios y descuentos por lote y valida disponibilidad de unidades.",
  },
  {
    id: 508,
    title: "Devoluciones y anulaciones",
    section: "Facturación",
    roleAccess: [1, 2],
    contentType: "text",
    text: "Para revertir una venta, ubica la factura desde Reportes o el historial diario y usa la opcion de devolucion/anulacion. El sistema suma las cantidades devueltas al lote original y registra el motivo. Genera comprobante de devolucion cuando aplique y revisa el stock resultante.",
  },
  {
    id: 509,
    title: "Movimientos de inventario y ajustes",
    section: "Inventario",
    roleAccess: [1, 3, 4],
    contentType: "text",
    text: "En Inventario > Resumen revisa existencias y stock minimo. Usa ajustes para corregir diferencias: salida por merma, entrada por conteo, traslado entre lotes. Cada accion queda en historial con usuario, detalle y fecha para auditoria.",
  },
  {
    id: 510,
    title: "Vencimientos y control de merma",
    section: "Inventario",
    roleAccess: [1, 3, 4],
    contentType: "text",
    text: "Configura dias de alerta en Reportes para ver lotes proximos a vencer. Prioriza su venta o realiza salida por merma antes de la fecha. Marca lotes inactivos para evitar que se ofrezcan en POS y mantener trazabilidad.",
  },
  {
    id: 511,
    title: "Proveedores y condiciones de compra",
    section: "Compras",
    roleAccess: [1, 3, 4],
    contentType: "text",
    text: "En Proveedores registra razon social, contacto, telefono, correo y condiciones de pago. Al crear compras selecciona el proveedor para conservar historico de costos y referencias. Mantener datos completos agiliza conciliaciones y reclamos.",
  },
  {
    id: 512,
    title: "Marcas, categorias y unidades de medida",
    section: "Productos",
    roleAccess: [1, 3, 4],
    contentType: "text",
    text: "Organiza el catalogo con categorias y marcas para reportes mas claros. Define unidad de medida y factor de conversion para que los lotes manejen empaques y unidades minimas correctamente. Actualizar estas entidades no altera historicos.",
  },
  {
    id: 513,
    title: "Seguridad y sesiones",
    section: "Usuarios",
    roleAccess: [1, 2, 3, 4],
    contentType: "text",
    text: "Cada usuario inicia con su rol y token JWT. Cierra sesion al terminar turno. Admin puede desactivar cuentas y cambiar contrasenas. Evita compartir credenciales: las acciones se registran con usuario para auditoria.",
  },
  {
    id: 514,
    title: "Exportacion y respaldos rapidos",
    section: "Reportes",
    roleAccess: [1, 4],
    contentType: "text",
    text: "Usa las opciones de exportar a Excel/PDF en reportes e inventario para respaldar cortes diarios. Incluye filtros de fecha y estado antes de exportar para archivos mas ligeros. Conserva copias de reportes de ventas y vencimientos como soporte de auditoria.",
  },
  {
    id: 515,
    title: "Atajos operativos diarios",
    section: "Resumen",
    roleAccess: [1, 2, 3, 4],
    contentType: "text",
    text: "Rutina sugerida: 1) Revisar dashboard y vencimientos. 2) Ingresar compras/lotes recibidos. 3) Ejecutar ventas y devoluciones. 4) Verificar stock bajo y reponer. 5) Exportar reportes clave. 6) Cerrar sesion. Esto mantiene data fresca y trazable.",
  },
];
